/**
 * @author: ercarval
 */
public class ZipCodeAddress {

    @AuraEnabled
    public String logradouro {get; set;}

    @AuraEnabled
    public String complemento {get; set;}

    @AuraEnabled
    public String bairro {get; set;}

    @AuraEnabled
    public String cep {get; set;}

    @AuraEnabled
    public String localidade {get; set;}

    @AuraEnabled
    public String uf {get; set;}

    @AuraEnabled
    public String unidade {get; set;}

    @AuraEnabled
    public String ibge {get; set;}

    @AuraEnabled
    public String gia {get; set;}

}